<?php

namespace Proxies\__CG__\GlavBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Servicio extends \GlavBundle\Entity\Servicio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'hash', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id_cliente', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id_empleado', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id_automotor', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id_rubro', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'estadoServicio', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'observacion', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'pago', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'fecha_servicio', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'fecha_entrega', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'estado', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'fecha');
        }

        return array('__isInitialized__', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'hash', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id_cliente', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id_empleado', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id_automotor', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'id_rubro', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'estadoServicio', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'observacion', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'pago', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'fecha_servicio', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'fecha_entrega', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'estado', '' . "\0" . 'GlavBundle\\Entity\\Servicio' . "\0" . 'fecha');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Servicio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHash($hash)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHash', array($hash));

        return parent::setHash($hash);
    }

    /**
     * {@inheritDoc}
     */
    public function getHash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHash', array());

        return parent::getHash();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCliente($idCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCliente', array($idCliente));

        return parent::setIdCliente($idCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', array());

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmpleado($idEmpleado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmpleado', array($idEmpleado));

        return parent::setIdEmpleado($idEmpleado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmpleado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmpleado', array());

        return parent::getIdEmpleado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAutomotor($idAutomotor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAutomotor', array($idAutomotor));

        return parent::setIdAutomotor($idAutomotor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAutomotor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAutomotor', array());

        return parent::getIdAutomotor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstadoServicio($idEstadoServicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstadoServicio', array($idEstadoServicio));

        return parent::setIdEstadoServicio($idEstadoServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstadoServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstadoServicio', array());

        return parent::getIdEstadoServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaServicio($fechaServicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaServicio', array($fechaServicio));

        return parent::setFechaServicio($fechaServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaServicio', array());

        return parent::getFechaServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEntrega($fechaEntrega)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEntrega', array($fechaEntrega));

        return parent::setFechaEntrega($fechaEntrega);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEntrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEntrega', array());

        return parent::getFechaEntrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdServicioEstado(\GlavBundle\Entity\ServicioEstado $idServicioEstado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdServicioEstado', array($idServicioEstado));

        return parent::setIdServicioEstado($idServicioEstado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdServicioEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdServicioEstado', array());

        return parent::getIdServicioEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRubro(\GlavBundle\Entity\Rubro $idRubro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRubro', array($idRubro));

        return parent::setIdRubro($idRubro);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRubro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRubro', array());

        return parent::getIdRubro();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoServicio($estadoServicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoServicio', array($estadoServicio));

        return parent::setEstadoServicio($estadoServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoServicio', array());

        return parent::getEstadoServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setPago($pago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPago', array($pago));

        return parent::setPago($pago);
    }

    /**
     * {@inheritDoc}
     */
    public function getPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPago', array());

        return parent::getPago();
    }

}
