<?php

namespace GlavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacturaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaDetalleRepository extends EntityRepository
{
}
